### ISSUE TITLE
看博主博客有 dark 风格的, 这里的 resp 支持吗

### ISSUE THREAD

**Issue by Aaaaaaron** [lotabout/hexo-theme-noise#13]
RT: https://lotabout.me/

**Comment by Aaaaaaron** [comment]
方便的话可以加个微信吗:
245915794

**Comment by lotabout** [comment]
支持，默认开启，目前没有开关

**Comment by Aaaaaaron** [comment]
最近又想换白色了 阔以支持吗😂

**Comment by lotabout** [comment]
@Aaaaaaron 啥意思…现在默认支持的方式自适应

**Comment by Aaaaaaron** [comment]
@lotabout 就是希望有显示开关的方式来设置黑/白

**Comment by Aaaaaaron** [comment]
https://aaaaaaron.github.io/ 话说我配置了 archive, 但是页面上没有, 这个是不是不同符合预期:
```
# Header
menu:
  ## If your site is put in a subdirectory, set Home as '/child/'
  Home: /
  Archives: archives
  About: about

social:
  email: tao@apache.org
  twitter:
  weibo:
  github: github.com/aaaaaaron/
  googleplus:
  rss: /atom.xml

# Content
fancybox: true # set to true if you want to use it
infinite_scroll: false # set to true if you want to use it
toc_words: "Table of Contents" # the line shown in toc
show_toc_by_default: true # to show toc if `toc:` is not specified in post
compact_index: false # to use compact version of index page

duoshuo: #duoshuo_shortname
disqus: #disqus _shortname
google_analytics: #Google Analytics Tracking Code
google_adsense_page_level_ads: #Google Adsense Page Level Ads Code

less:
  paths:
    - source/css
  compress:
    true

```
