### ISSUE TITLE
run hexo server and goto index page, then website is broken.

### ISSUE THREAD

**Issue by dravenk** [lotabout/hexo-theme-noise#4]
Error message：  
```
extends base - var current_title = page.title || tag.name || category.name || site.title block title title= config.title + " | " + config.subtitle block main // Blog title and subtitle header.wrapper.header .container.blog-title a#logo.title(href=url_for('.'))= config.title span.subtitle= config.subtitle label#toggle-menu(for="menu", onclick) i.fa.fa-bars // use checkbox hack for toggle nav-bar on small screens input#menu(type="checkbox") .container.nav-items each nav, name in theme.menu +a_with_current(nav, __(name)) article.wrapper #index-main.container.entries for post in page.posts.toArray() .post-entry .post-desc .post-title if post.link a(href=url_for(post.link),target="_blank", itemprop="url")= post.title else a(href=url_for(post.path))= post.title .post-content if post.description != post.description else if post.excerpt != post.excerpt else if post.content - var br = post.content.indexOf('
') if br < 0 != post.content else != post.content.substring(0, br + 4) .post-meta if (post.tags && post.tags.length) .post-tags != list_tags(post.tags, {show_count: false, class: 'post-tag', style:'none', separator:''}) .post-time= post.date.format(config.date_format) include _partial/paginator.jade footer.footer.wrapper .social +social_icon('email', "mailto:", "fa-envelope-o") +social_icon('twitter', 'http://twitter.com/', 'fa-twitter') +social_icon('weibo', 'http://weibo.com/', 'fa-weibo') +social_icon('github', 'https://github.com/', 'fa-github') +social_icon('googleplus', 'https://plus.google.com/', 'fa-google-plus') +social_icon('rss', "", "fa-rss") .footer-content - var year = date(new Date(), 'YYYY'); = 'Â© ' + year + ' ' a(href='/', rel='nofollow')= config.title = '. Powered by ' a(rel='nofollow', target='_blank', href='https://hexo.io') Hexo = '. Theme ' a(target='_blank', href='https://github.com/lotabout/hexo-theme-noise') noise |.
```

**Comment by lotabout** [comment]
@DravenK If possible, please provide your `_config.yml`, and hexo version.

**Comment by dravenk** [comment]
This is a config.yml of sanbox. 
```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo
subtitle:
description:
author: John Doe
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-noise

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:
```
